### ISSUE TITLE
Possible to use project with EBYTE E220-900T30D?

### ISSUE THREAD

**Issue by Schawen** [xreef/EByte-LoRa-Manager-esp32-Gateway#1]
I got 2 modules of EBYTE E220-900T30D.
Are there any objections to use these modules?

**Comment by xreef** [comment]
Hi,
E220 has a different configuration setting, so it can't be configured ad e32.
If I find some time I try to implement the version for 220.
Bye Renzo

**Comment by Schawen** [comment]
Thanks for your fast response!
I'm looking forward to test this nice looking project.
Bye Sven
